name: hello_world
description: TP Blockchain DApp
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Dépendances mises à jour pour Flutter 3.38
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  web3dart: ^2.6.1
  http: ^1.1.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # Ce fichier doit exister grâce à Truffle
    - src/artifacts/HelloWorld.json